---
environment: production
chdir: /opt/engines/src/server
address: 0.0.0.0
port: 2380
pid: /home/engines/run/system.pid
log: /var/log/system.log
max_conns: 102
no-epoll: true
timeout: 300
wait: 300
max_persistent_conns: 12
daemonize: false
