FROM engines/frameworkbuild:$release

ADD home home
ENV ContUser node
ENV ContGrp node
ENV NODE_VERSION 12.16.1
ENV ARCHIVE node-v12.16.1-linux-x64.tar.xz
ENV SRC_URL=https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz


