FROM engines/frameworkbuild:$release

ADD home home
ENV ContUser node
ENV ContGrp node
ENV NODE_VERSION 10.47
#RUN mkdir ~/node_js_src && cd $_;wget -N http://nodejs.org/dist/latest-v0.12.x/node-v${NODE_VERSION}.tar.xz;tar xvf node-v0.12.17.tar.xz && cd node-v0.12.17;./configure; make ;make install;\
#	groupadd node;\
# 	useradd -u 22673  -g node -d /home/node -m -G containers node&&\
# 	npm -g install npm@latest;\
# 	cd ~ ; rm -r ~/node_js_src  
#