FROM debian:wheezy

RUN apt-get -y  --force-yes update;\
	apt-get -y  --force-yes upgrade;\
	apt-get -y  --force-yes update;\
	apt-get -y  --fix-missing install   unzip  curl dnsutils git  wget bzip2 zlibc;\ 
	mkdir -p /var/run

ADD ddns.key /etc/
ADD ddns.private /etc/
ADD dns-init.sh /home/
#ADD init.sh /home/
