---
environment: production
chdir: /home/app
address: 0.0.0.0
port: 8000
pid: /home/engines/run/uadmin.pid
log: /var/log/system.log
max_conns: 1024
timeout: 60
max_persistent_conns: 512
daemonize: false
