
RUN mkdir /node_js_src &&\
	cd /node_js_src &&\
	wget -N ${SRC_URL}  &&\
	tar -xvf node-${NODE_VERSION}.tar.gz &&\
	rm -xvf node-${NODE_VERSION}.tar.gz &&\
	cd node-* &&\
	./configure &&\
	make &&\
	make install &&\
	groupadd node ;\
 	useradd -g node -d /home/node -m -G containers node ;\
 	npm -g install npm@latest &&\
 	cd / ; rm -r /node_js_src
 	 