#! /bin/sh

#taken from https://gist.github.com/specialunderwear/1218856
# and edited 
#eo removed

cd /usr/share/locales
./install-language-pack ia
./install-language-pack ie
./install-language-pack io
./install-language-pack vo
./install-language-pack ca
./install-language-pack fr_AD
./install-language-pack ar_AE
./install-language-pack fa_AF
./install-language-pack ps
./install-language-pack ug
./install-language-pack uz_AF
./install-language-pack en_AG
./install-language-pack en_AI
./install-language-pack sq
./install-language-pack hy
./install-language-pack nl_AN
./install-language-pack kg
./install-language-pack kj
./install-language-pack pt_AO
./install-language-pack cy_AR
./install-language-pack es_AR
./install-language-pack gn
./install-language-pack en_AS
./install-language-pack sm
./install-language-pack de_AT
./install-language-pack hu
./install-language-pack en_AU
./install-language-pack nl_AW
./install-language-pack sv_AX
./install-language-pack av
./install-language-pack az
./install-language-pack os
./install-language-pack bs
./install-language-pack hr_BA
./install-language-pack sr_BA
./install-language-pack en_BB
./install-language-pack bn_BD
./install-language-pack de_BE
./install-language-pack en_BE
./install-language-pack fr_BE
./install-language-pack nl_BE
./install-language-pack wa
./install-language-pack yi
./install-language-pack bm
./install-language-pack fr_BF
./install-language-pack ha
./install-language-pack bg
./install-language-pack cu
./install-language-pack tr_BG
./install-language-pack ar_BH
./install-language-pack fr_BI
./install-language-pack rn
./install-language-pack fr_BJ
./install-language-pack en_BM
./install-language-pack en_BN
./install-language-pack ms_BN
./install-language-pack ay
./install-language-pack es_BO
./install-language-pack pt_BR
./install-language-pack en_BS
./install-language-pack dz
./install-language-pack ne
./install-language-pack en_BW
./install-language-pack sn
./install-language-pack tn_BW
./install-language-pack be
./install-language-pack cu
./install-language-pack yi
./install-language-pack en_BZ
./install-language-pack cr
./install-language-pack en_CA
./install-language-pack fr_CA
./install-language-pack iu
./install-language-pack oj
./install-language-pack yi
./install-language-pack ms_CC
./install-language-pack fr_CD
./install-language-pack kg
./install-language-pack ln_CD
./install-language-pack lu
./install-language-pack fr_CF
./install-language-pack sg
./install-language-pack fr_CG
./install-language-pack kg
./install-language-pack ln_CG
./install-language-pack de_CH
./install-language-pack fr_CH
./install-language-pack it_CH
./install-language-pack rm
./install-language-pack ak
./install-language-pack bm
./install-language-pack fr_CI
./install-language-pack en_CK
./install-language-pack ay
./install-language-pack es_CL
./install-language-pack en_CM
./install-language-pack fr_CM
./install-language-pack bo
./install-language-pack ii
./install-language-pack za
./install-language-pack zh_CN
./install-language-pack es_CO
./install-language-pack es_CR
./install-language-pack cu
./install-language-pack hu
./install-language-pack sq
./install-language-pack sr
./install-language-pack es_CU
./install-language-pack pt_CV
./install-language-pack ms_CC
./install-language-pack el_CY
./install-language-pack tr_CY
./install-language-pack cs
./install-language-pack da_DE
./install-language-pack da_DE
./install-language-pack de_DE
./install-language-pack de
./install-language-pack dsb
./install-language-pack fy_DE
./install-language-pack hsb
./install-language-pack lb
./install-language-pack nds
./install-language-pack wen
./install-language-pack yi
./install-language-pack aa_DJ
./install-language-pack fr_DJ
./install-language-pack so_DJ
./install-language-pack da_DK
./install-language-pack de_DK
./install-language-pack en_DM
./install-language-pack es_DO
./install-language-pack ar_DZ
./install-language-pack es_EC
./install-language-pack et
./install-language-pack yi
./install-language-pack ar_EG
./install-language-pack aa_ER
./install-language-pack byn
./install-language-pack en_ER
./install-language-pack gez_ER
./install-language-pack ti_ER
./install-language-pack tig
./install-language-pack an
./install-language-pack ca
./install-language-pack es_ES
./install-language-pack eu
./install-language-pack gl
./install-language-pack aa_ET
./install-language-pack am
./install-language-pack en_ET
./install-language-pack gez_ET
./install-language-pack om_ET
./install-language-pack sid
./install-language-pack so_ET
./install-language-pack ti_ET
./install-language-pack wal
./install-language-pack fi_FI
./install-language-pack smn
./install-language-pack sv_FI
./install-language-pack en_FJ
./install-language-pack fj
./install-language-pack en_FK
./install-language-pack en_FM
./install-language-pack da_FO
./install-language-pack fo
./install-language-pack br
./install-language-pack co
./install-language-pack de_FR
./install-language-pack fr_FR
./install-language-pack oc
./install-language-pack fr_GA
./install-language-pack cy_GB
./install-language-pack en_GB
./install-language-pack fr_GB
./install-language-pack ga_GB
./install-language-pack gd
./install-language-pack gv
./install-language-pack kw
./install-language-pack en_GD
./install-language-pack ab
./install-language-pack ka
./install-language-pack os
./install-language-pack fr_GF
./install-language-pack ak
./install-language-pack ee
./install-language-pack en_GH
./install-language-pack tw
./install-language-pack en_GI
./install-language-pack da_GL
./install-language-pack kl
./install-language-pack bm
./install-language-pack en_GM
./install-language-pack wo
./install-language-pack fr_GN
./install-language-pack fr_GP
./install-language-pack es_GQ
./install-language-pack el_GR
./install-language-pack es_GT
./install-language-pack ch_GU
./install-language-pack en_GU
./install-language-pack pt_GW
./install-language-pack en_GY
./install-language-pack en_HK
./install-language-pack zh_Hant_HK
./install-language-pack zh_HK
./install-language-pack es_HN
./install-language-pack hr_HR
./install-language-pack it_HR
./install-language-pack fr_HT
./install-language-pack ht
./install-language-pack de_HU
./install-language-pack hu_HU
./install-language-pack sk_HU
./install-language-pack sr_HU
./install-language-pack id
./install-language-pack jv
./install-language-pack su
./install-language-pack en_IE
./install-language-pack ga_IE
./install-language-pack ar_IL
./install-language-pack en_IL
./install-language-pack he
./install-language-pack yi
./install-language-pack ar_IN
./install-language-pack as
./install-language-pack bh
./install-language-pack bn_IN
./install-language-pack en_IN
./install-language-pack gu
./install-language-pack hi
./install-language-pack kn
./install-language-pack kok
./install-language-pack ks
./install-language-pack ml
./install-language-pack mr
./install-language-pack ne
./install-language-pack or
./install-language-pack pa
./install-language-pack pi
./install-language-pack sa
./install-language-pack sd_IN
./install-language-pack ta_IN
./install-language-pack te
./install-language-pack ur_IN
./install-language-pack en_IO
./install-language-pack ar_IQ
./install-language-pack ku
./install-language-pack ae
./install-language-pack fa_IR
./install-language-pack ku
./install-language-pack is
./install-language-pack co
./install-language-pack de_IT
./install-language-pack fr_IT
./install-language-pack it_IT
./install-language-pack sc
./install-language-pack en_JM
./install-language-pack ar_JO
./install-language-pack ja
./install-language-pack en_KE
./install-language-pack ki
./install-language-pack om_KE
./install-language-pack so_KE
./install-language-pack sw_KE
./install-language-pack ky
./install-language-pack ug
./install-language-pack km
./install-language-pack en_KI
./install-language-pack fr_KM
./install-language-pack en_KN
./install-language-pack ko_KP
./install-language-pack ko_KR
./install-language-pack ar_KW
./install-language-pack en_KY
./install-language-pack av
./install-language-pack kk
./install-language-pack os
./install-language-pack ug
./install-language-pack lo
./install-language-pack ar_LB
./install-language-pack fr_LB
./install-language-pack en_LC
./install-language-pack de_LI
./install-language-pack si
./install-language-pack en_LR
./install-language-pack en_LS
./install-language-pack st
./install-language-pack xh
./install-language-pack lt
./install-language-pack yi
./install-language-pack de_LU
./install-language-pack fr_LU
./install-language-pack lb
./install-language-pack lv
./install-language-pack yi
./install-language-pack ar_LY
./install-language-pack ar_MA
./install-language-pack fr_MC
./install-language-pack mo
./install-language-pack ro
./install-language-pack tr
./install-language-pack uk
./install-language-pack yi
./install-language-pack fr_MG
./install-language-pack mg
./install-language-pack en_MH
./install-language-pack mh
./install-language-pack cu
./install-language-pack mk
./install-language-pack bm
./install-language-pack fr_ML
./install-language-pack my
./install-language-pack mn
./install-language-pack zh_MO
./install-language-pack ch_MP
./install-language-pack en_MP
./install-language-pack fr_MQ
./install-language-pack ar_MR
./install-language-pack wo
./install-language-pack en_MS
./install-language-pack en_MT
./install-language-pack mt
./install-language-pack en_MU
./install-language-pack dv
./install-language-pack en_MW
./install-language-pack ny
./install-language-pack es_MX
./install-language-pack jv
./install-language-pack ms_MY
./install-language-pack pt_MZ
./install-language-pack sn
./install-language-pack en_NA
./install-language-pack hz
./install-language-pack ng
./install-language-pack fr_NC
./install-language-pack ff_NE
./install-language-pack fr_NE
./install-language-pack ha
./install-language-pack kr
./install-language-pack en_NF
./install-language-pack en_NG
./install-language-pack ff_NG
./install-language-pack ha
./install-language-pack ig
./install-language-pack kr
./install-language-pack yo
./install-language-pack es_NI
./install-language-pack fy_NL
./install-language-pack li
./install-language-pack nl_NL
./install-language-pack nb
./install-language-pack nn
./install-language-pack no
./install-language-pack ne
./install-language-pack en_NR
./install-language-pack na
./install-language-pack en_NU
./install-language-pack en_NZ
./install-language-pack mi
./install-language-pack ar_OM
./install-language-pack es_PA
./install-language-pack ay
./install-language-pack es_PE
./install-language-pack qu
./install-language-pack fr_PF
./install-language-pack ty
./install-language-pack en_PG
./install-language-pack ho
./install-language-pack en_PH
./install-language-pack tl
./install-language-pack en_PK
./install-language-pack sd_PK
./install-language-pack ur_PK
./install-language-pack de_PL
./install-language-pack pl
./install-language-pack yi
./install-language-pack fr_PM
./install-language-pack en_PN
./install-language-pack en_PR
./install-language-pack es_PR
./install-language-pack ar_PS
./install-language-pack pt_PT
./install-language-pack en_PW
./install-language-pack es_PY
./install-language-pack gn
./install-language-pack ar_QA
./install-language-pack fr_RE
./install-language-pack cu
./install-language-pack hu
./install-language-pack ro
./install-language-pack av
./install-language-pack ba
./install-language-pack ce
./install-language-pack cu
./install-language-pack cv
./install-language-pack kv
./install-language-pack os
./install-language-pack ru_RU
./install-language-pack tt
./install-language-pack yi
./install-language-pack en_RW
./install-language-pack fr_RW
./install-language-pack rw
./install-language-pack ar_SA
./install-language-pack en_SB
./install-language-pack en_SC
./install-language-pack fr_SC
./install-language-pack ar_SD
./install-language-pack din
./install-language-pack ha
./install-language-pack fi_SE
./install-language-pack se
./install-language-pack sma
./install-language-pack sme
./install-language-pack sv_SE
./install-language-pack bn_SG
./install-language-pack en_SG
./install-language-pack ms_SG
./install-language-pack ta_SG
./install-language-pack zh_Hans_SG
./install-language-pack zh_SG
./install-language-pack en_SH
./install-language-pack hu_SI
./install-language-pack it_SI
./install-language-pack hu
./install-language-pack sk
./install-language-pack en_SL
./install-language-pack it_SM
./install-language-pack ff_SN
./install-language-pack wo
./install-language-pack ar_SO
./install-language-pack en_SO
./install-language-pack so_SO
./install-language-pack jv
./install-language-pack nl_SR
./install-language-pack pt_ST
./install-language-pack es_SV
./install-language-pack ar_SY
./install-language-pack syr
./install-language-pack en_SZ
./install-language-pack ss_SZ
./install-language-pack en_TC
./install-language-pack ar_TD
./install-language-pack fr_TD
./install-language-pack ee
./install-language-pack fr_TG
./install-language-pack ha
./install-language-pack si
./install-language-pack th
./install-language-pack os
./install-language-pack tg
./install-language-pack ug
./install-language-pack en_TK
./install-language-pack pt_TL
./install-language-pack os
./install-language-pack tk
./install-language-pack ar_TN
./install-language-pack en_TO
./install-language-pack to
./install-language-pack ab
./install-language-pack av
./install-language-pack ku
./install-language-pack tr_TR
./install-language-pack ug
./install-language-pack en_TT
./install-language-pack gil
./install-language-pack tvl
./install-language-pack zh_TW
./install-language-pack sw_TZ
./install-language-pack ab
./install-language-pack cu
./install-language-pack hu
./install-language-pack os
./install-language-pack pl
./install-language-pack ro
./install-language-pack ru_UA
./install-language-pack uk
./install-language-pack yi
./install-language-pack en_UG
./install-language-pack lg
./install-language-pack en_UM
./install-language-pack en_US
./install-language-pack es_US
./install-language-pack haw
./install-language-pack ik
./install-language-pack nv
./install-language-pack oj
./install-language-pack yi
./install-language-pack es_UY
./install-language-pack os
./install-language-pack ug
./install-language-pack uz_UZ
./install-language-pack fr
./install-language-pack it
./install-language-pack la
./install-language-pack en_VC
./install-language-pack es_VE
./install-language-pack en_VG
./install-language-pack en_VI
./install-language-pack vi
./install-language-pack bi
./install-language-pack en_VU
./install-language-pack fr_VU
./install-language-pack fr_WF
./install-language-pack en_WS
./install-language-pack sm
./install-language-pack ar_YE
./install-language-pack fr_YT
./install-language-pack af
./install-language-pack en_ZA
./install-language-pack nr
./install-language-pack ss_ZA
./install-language-pack tn_ZA
./install-language-pack ts
./install-language-pack ve
./install-language-pack xh
./install-language-pack yi
./install-language-pack zu
./install-language-pack en_ZM
./install-language-pack en_ZW
./install-language-pack nd
./install-language-pack sn
./install-language-pack ve
./install-language-pack zu
dpkg-reconfigure locales