---
environment: production
chdir: /home/app/control
address: 0.0.0.0
port: 8001
pid: /home/engines/run/control.pid
log: /var/log/control.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false
