---
environment: production
chdir: /home/app
address: 0.0.0.0
port: 8484
pid: /engines/var/run/control.pid
log: /var/log/controlcontrol.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false
