---
environment: production
chdir: /home/app
address: 0.0.0.0
port: 4567
pid: /engines/var/run/firstrun.pid
log: /var/log/firstrun.log
max_conns: 10
timeout: 30
max_persistent_conns: 10
daemonize: false
